[package]
name = "p3-goldilocks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
nightly-features = []

[dependencies]
num-bigint = { workspace = true, default-features = false }
p3-dft.workspace = true
p3-field.workspace = true
p3-mds.workspace = true
p3-poseidon2.workspace = true
p3-symmetric.workspace = true
p3-util.workspace = true
rand.workspace = true
rustversion.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
criterion.workspace = true
p3-field-testing.workspace = true
p3-poseidon.workspace = true
rand = { workspace = true, features = ["min_const_gen"] }

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
