[package]
name = "p3-symmetric"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
itertools = { version = "0.13.0", default-features = false, features = ["use_alloc"] }
p3-field = { path = "../field" }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
