[package]
name = "p3-field"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
num-bigint = { workspace = true, default-features = false }
num-integer = { workspace = true, default-features = false }
num-traits = { workspace = true, default-features = false }
p3-util.workspace = true

itertools = { workspace = true, default-features = false, features = ["use_alloc"] }
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
